### ISSUE TITLE
Renaming repo strategy

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#536]
Before releasing `reason-react-native` I want to rename this repo to `reason-react-native`. But by doing to we will break things a little bit

- old website links etc will be dead
- all people using bs-react-native/reason-react-native might have failure locally & on ci

So I propose the following

- renaming repo to `reason-react-native`
- forking the newly created repo as `bs-react-native`
- cleaning README of the fresh for & say in bold "MOVED" with details & redirect link
- (optional: in a month or 2, completely removing the code in bs-react-native fork repo ?)

Also I think we should,  

- cleaning old website with a some (meta) redirect to the new one
- removing legacy docs from the new website (totally unecessary to keep those)
- only keeping legacy docs on bs-react-native url & use redirect for the home (https://reasonml-community.github.io/bs-react-native/)

Thoughts?

**Comment by fakenickels** [comment]
I really like this plan!
I don't have any objections, not sure if someone else will spot any gotchas

**Comment by wokalski** [comment]
@MoOx perfect. I wouldn't remove the newly created `bs-react-native` repo though :+1:

**Comment by MoOx** [comment]
@wokalski My idea is to clean the code of the repo so we quickly get the readme. bs-react-native current code will be properly archived & kept accessible for sure

**Comment by MoOx** [comment]
Going to do that in an hour or two if I don't get any objections

**Comment by MoOx** [comment]
WIP, I have some issues with CI but trying to fix these.

**Comment by sgny** [comment]
How about removing `bs-react-native` from this repo altogether now that we have the JSX 3 compatible version of those bindings?

**Comment by MoOx** [comment]
Don't want to do this right now, I want to wait a little bit in order to add a new release in a few weeks/month in the README (for npm) & even use an npm deprecation notice in 6 months.

**Comment by MoOx** [comment]
This is not relevant anymore.
