### ISSUE TITLE
Migrate packages dependent on bs-react-native

### ISSUE THREAD

**Issue by Maushundb** [reason-react-native/reason-react-native#548]
Lot of packages depend on `bs-react-native`, such as [this](https://github.com/Astrocoders/bs-react-native-vector-icons/blob/922dd9a99ea60ea2b144f1ff4b10176daf1d1f15/package.json#L23). We'll need to work with these package owners to migrate to the next release of reason-react-native. 

Preliminary list from [npm search](https://www.npmjs.com/search?q=bs-react-native&page=0&perPage=20):

- [x] bs-react-native-paper
- [x] bs-react-native-vector-icons
- [ ] bs-react-native-masked-text
- [ ] bs-react-navigation
- [x] react-from-svg
- [x] bs-react-native-linear-gradient
- [x] @cca-io/bs-react-native-device-info
- [x] @cca-io/bs-rn-fetch-blob
- [x] @cca-io/bs-react-navigation
- [ ] react-native-nepali-date
- [ ] bs-react-native-websocket
- [ ] bs-lottie-react-native
- [ ] bs-react-native-gifted-chat
- [ ] bs-react-native-modal
- [ ] bs-expo
- [ ] bs-react-native-image-picker
- [ ] bs-react-native-typography
- [ ] @lewisf/bs-react-native-typography
- [ ] bs-react-native-navigation
- [ ] bs-react-native-mixpanel
- [ ] bs-react-native-material-ui
- [ ] rnw-bs
- [ ] bs-react-native-elements
- [ ] bs-react-native-router-flux
- [ ] bs-react-native-action-sheet
- [ ] bs-react-native-facebook-login
- [ ] ~~@jaredly/bs-react-native~~

**Comment by sgny** [comment]
Perhaps we should revive our discussion on listing available bindings somewhere. I added both these and [`reason-react-native-maps`](https://www.npmjs.com/package/reason-react-native-maps) to [redex](https://redex.github.io). we could perhaps add a link to that directory at the least.

**Comment by MoOx** [comment]
Yeah probably.
We could also provide a curated list of bindings

**Comment by cknitt** [comment]
I'll update ours (`@cca-io/*`) when I have some time later this week.

**Comment by idkjs** [comment]
https://github.com/callstackincubator/bs-react-native-paper.git

**Comment by cknitt** [comment]
Updated `@cca-io/bs-rn-fetch-blob`.

**Comment by cknitt** [comment]
Updated `@cca-io/bs-react-native-device-info`.

**Comment by cknitt** [comment]
Updated `@cca-io/bs-react-navigation`.

**Comment by fakenickels** [comment]
Working on https://github.com/callstackincubator/bs-react-native-paper/pull/79

**Comment by ikewat** [comment]
Is there any dedicated Navigation package to work with `reason-react-native`?

I'm trying to migrate my project from `bs-react-native` to `reason-react-native`.
Most goes well, except  I was using `callstackincubator/bs-react-navigation` and it seems deprecated.

**Comment by MoOx** [comment]
@ikewat You can try this https://github.com/reasonml-community/reason-react-native/tree/master/reason-react-navigation using the git monorepo trick https://github.com/reasonml-community/reason-react-native#-usage-from-git-repo as it's not released yet (WIP subject to changes)

**Comment by MoOx** [comment]
What would be nice is to have number of npm download so we can focus on what is actually used (& so required) by the community.
Can someone try to do something like I just did on #594 ?

**Comment by idkjs** [comment]
<https://www.npmjs.com/package/bs-react-native-paper> has 666 downloads.
<https://www.npmjs.com/package/bs-react-native-vector-icons> has 364 downloads.
<https://www.npmjs.com/package/bs-react-native-image-picker> has 110 downloads.
<https://www.npmjs.com/package/bs-react-native-action-sheet> has 42 downloads.
<https://www.npmjs.com/package/@cca-io/bs-react-native-device-info> has 33 downloads.
<https://www.npmjs.com/package/react-from-svg> has 31 downloads.
<https://www.npmjs.com/package/react-native-nepali-date> has 29 downloads.
<https://www.npmjs.com/package/@cca-io/bs-rn-fetch-blob> has 19 downloads.
<https://www.npmjs.com/package/@lewisf/bs-react-native-typography> has 16 downloads.
<https://www.npmjs.com/package/bs-react-navigation> has 13 downloads.
<https://www.npmjs.com/package/rnw-bs> has 13 downloads.
<https://www.npmjs.com/package/bs-react-native-mixpanel> has 11 downloads.
<https://www.npmjs.com/package/bs-lottie-react-native> has 10 downloads.
<https://www.npmjs.com/package/bs-react-native-modal> has 10 downloads.
<https://www.npmjs.com/package/bs-expo> has 10 downloads.
<https://www.npmjs.com/package/bs-react-native-websocket> has 8 downloads.
<https://www.npmjs.com/package/bs-react-native-gifted-chat> has 8 downloads.
<https://www.npmjs.com/package/bs-react-native-elements> has 8 downloads.
<https://www.npmjs.com/package/bs-react-native-masked-text> has 8 downloads.
<https://www.npmjs.com/package/bs-react-native-material-ui> has 7 downloads.
<https://www.npmjs.com/package/bs-react-native-typography> has 7 downloads.
<https://www.npmjs.com/package/bs-react-native-linear-gradient> has 7 downloads.
<https://www.npmjs.com/package/bs-react-native-navigation> has 6 downloads.
<https://www.npmjs.com/package/bs-react-native-router-flux> has 5 downloads.
<https://www.npmjs.com/package/bs-react-native-facebook-login> has 5 downloads.

> Error! package @cca-io/bs-react-navigation not found

**Comment by mitulsavani** [comment]
can anyone please give me a pointer on how would I go about working on this? I did look under closed PR and didn't find anything related to this issue.

**Comment by idkjs** [comment]
@mitulsavani greetings, friend. I would fork whatever pack you want to work on then hack at it. Maybe run https://github.com/bloodyowl/upgrade-reason-react-esy on it and get some guidance from the upgrade script in this repo here: https://github.com/reasonml-community/reason-react-native/blob/master/website/docs/migration/jsx3.md

**Comment by Naturalclar** [comment]
made a package for `react-native-linear-gradient` that's compatible with `reason-react-native`. that should work as a replacement for `bs-react-native-linear-gradient` 
https://github.com/Naturalclar/linear-gradient

**Comment by piotrdubiel** [comment]
I've updated [bs-react-native-lottie](https://github.com/piotrdubiel/bs-lottie) to support Reason React Native.

**Comment by MoOx** [comment]
I guess it's time to close this issue even if the work can be continued :)
