### ISSUE TITLE
AppRegistry bindings incomplete

### ISSUE THREAD

**Issue by cknitt** [reason-react-native/reason-react-native#561]
AppRegistry bindings are incomplete.

We currently have `registerComponent`, and #560 adds `registerHeadlessTask`, but there are more functions missing, see https://facebook.github.io/react-native/docs/appregistry.

**Comment by sgny** [comment]
Thanks for adding registerHeadlessTask.

I’ve had incomplete bindings to AppRegistry on hand for a very long time now, I’ll see if I can dig them out.

This API is rather poorly documented, I gave up because at least a few of them didn’t seem to work properly, at least with iOS.

**Comment by sgny** [comment]
OK, I still have them. I could not check before as I was on my phone.

I'll prepare a PR and we'll proceed from there.

**Comment by cknitt** [comment]
@sgny Great! Thanks a lot! 👍

**Comment by MoOx** [comment]
Closed by #567
