### ISSUE TITLE
Add better description for size and margin stuff

### ISSUE THREAD

**Issue by dmtrKovalenko** [reason-react-native/reason-react-native#571]
It was needed to dig into the source to understand that there are `pt` and `pct` types and what do they mean. 

It will be cool even to have this in example

**Comment by MoOx** [comment]
This isn’t enough? https://reasonml-community.github.io/reason-react-native/en/docs/apis/Style/#size

**Comment by dmtrKovalenko** [comment]
Yeah, thats enough. I didn't see this page 🤦‍♂ 
It is a bit confusing to see that in `Apis` section. Especially now when it is by default not visible. Will be cool to add the link from the example section, because developers that are familiar with react native will not read all the docs.
![image](https://user-images.githubusercontent.com/16926049/62829937-90b6b300-bc0d-11e9-8de3-81cc5912f1fb.png)

**Comment by dmtrKovalenko** [comment]
Feel free to close this one

**Comment by MoOx** [comment]
Did you tried the search field at the top of the site? Did you missed it?
(Real question, I really want to improve this situation as if you missed it, tons of people may have too)

**Comment by dmtrKovalenko** [comment]
Sure thing. 
I have stopped reading the docs just after the first `getting started section`. Because I thought that all the other things are ported from the original [react-native](https://facebook.github.io/react-native/docs/activityindicator) docs. BTW they don't have styles in API, because it is kinda fundamental thing and not something like clipboard.

Yeah for me it would be saved a lot of time to have additional styles point in the first section. Like some complex styling example and link to the api section

**Comment by MoOx** [comment]
I bet you didn't see the "complex" example  in the Cheatsheet page?

**Comment by dmtrKovalenko** [comment]
Ohh, I see :) 
```
          ~top=100.->dp,
          ~right=(-20.)->dp,
```

But it was soooo unclear for me that time

**Comment by MoOx** [comment]
Also search would have helped here :)

<img width="627" alt="image" src="https://user-images.githubusercontent.com/157534/62923130-597f0800-bdad-11e9-82cf-9b9a82459c87.png">

**Comment by MoOx** [comment]
I will think about that discussion a bit and will try to improve the situation as it's clear it's a very important point about the bindings.

**Comment by MoOx** [comment]
Website might be revisited soon.
