### ISSUE TITLE
git monorepo trick need to copy, not symlink

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/reason-react-native#581]
I created a project using 
```
npx react-native init MyApp --template reason-react-native-template cd MyApp
``` 

Then add `yarn add https://github.com/reasonml-community/reason-react-native` and `yarn add --dev symlink-dir`,

Then added scripts:
https://github.com/idkjs/AuthFlowReasonReactNativeDemo/blob/34603638e66829fbd563643121ad86085726880b/package.json#L12-L13

Then run `yarn install`:

output:
```bsh
warning ../../../package.json: No license field
$  symlink-dir ./node_modules/reason-react-native-monorepo/reason-react-native node_modules/reason-react-native && symlink-dir ./node_modules/reason-react-native-monorepo/reason-react-navigation node_modules/reason-react-navigation
✨  Done in 0.33s.
✨  Done in 6.40s.
```

Bucklescript compiles, then run `yarn start` && `yarn ios`.

Result is:

# Error

This is the screen error saying "Unable to resolve module reason-react-navigation/src/AppContainer.bs.js" when its there.

<img width="355" alt="Screen Shot 2019-08-20 at 11 47 18 AM" src="https://user-images.githubusercontent.com/2370391/63363617-ef80d880-c341-11e9-9c39-34d9803cb4af.png">

```bsh
Unable to resolve module `reason-react-navigation/src/AppContainer.bs.js` from `/Users/prisc_000/working/DEMOS/AuthFlow/src/AppNavigator.bs.js`: Module `reason-react-navigation/src/AppContainer.bs.js` does not exist in the Haste module map
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

[Reproduction](https://github.com/idkjs/AuthFlowReasonReactNativeDemo)

Same here using expo: https://github.com/idkjs/reason-auth-flow-demo.

I probably made the same mistake twice but can't tell what it is.

Thank you.

**Comment by MoOx** [comment]
This might still be an issue https://github.com/facebook/metro/issues/1

**Comment by MoOx** [comment]
this trick is the past, now that we don't rely on a monorepo, this is issue is not relevant anymore as you can directly use repos :)
