### ISSUE TITLE
Expose __DEV__

### ISSUE THREAD

**Issue by Natim** [reason-react-native/reason-react-native#588]
```reason
external __DEV__: bool = "__DEV__";
```

**Comment by MoOx** [comment]
We should probably have a global module for this.
We could do `ReactNative.Global.__DEV__` (so accessed via `Global.__DEV__`).
What do you think @cknitt @sgny ?

That would allow us to also place the very simple `alert(string)` & probably some other stuff?

**Comment by cknitt** [comment]
👍 for `ReactNative.Global`.

* `ReactNative.Global.__DEV__` feels a bit weird though. Maybe we should bind it as `ReactNative.Global.isDevMode`?
* In production, is it actually `false` or `undefined`?

**Comment by MoOx** [comment]
> ReactNative.Global.__DEV__ feels a bit weird though

Yeah but will look like what people know from JS. That's why I would like to keep it as is (at least for a start).

> In production, is it actually false or undefined?

I would guess `false` to trigger dead code removal, with undefined, not sure it's if this would work.

Also

https://github.com/facebook/metro/blob/6353fca5b29cf928002d7e97d80a028b748a28e4/packages/metro/src/lib/polyfills/require.js#L16

**Comment by sgny** [comment]
According to this [StackOverflow post](https://stackoverflow.com/questions/35421992/is-dev-defined-on-production), `__dev__` is undefined in production.

`undefined` is falsy in JavaScript, so perhaps dead-code elimination would still work as intended.

I will be trying out a few things over the weekend, if I can get to it, I'll also try to check this.

**Comment by sgny** [comment]
Checked; it's `false` for release builds.

**Comment by cknitt** [comment]
Great, thanks for checking! Then let's go ahead like @MoOx proposed.

**Comment by sgny** [comment]
@MoOx Any ideas where `Global.re` should go? Under `apis`?

**Comment by Natim** [comment]
> Should `Global.re` go under apis?

I guess so yes.
