### ISSUE TITLE
forwardRef

### ISSUE THREAD

**Issue by jfrolich** [reason-react-native/reason-react-native#592]
```reasonml
[@react.component]
let input =
  React.forwardRef((~children, (), ref) => <View ref> children </View>);
```
gives: 
```
  We've found a bug for you!
  Input

  This has type:
    ({. "children": React.element}, ReactNative.View.ref) => React.element
  But somewhere wanted:
    ({. "children": React.element}, Js.Nullable.t(React.Ref.t('a))) =>
    React.element

  The incompatible parts:
    ReactNative.View.ref (defined as
      React.Ref.t(Js.nullable(ReactNative.View.element)))
    vs
    Js.Nullable.t(React.Ref.t('a)) (defined as Js.nullable(React.Ref.t('a)))
```

Is there any way to do forward refs?

**Comment by cknitt** [comment]
I haven't really used `React.forwardRef` yet. I use refs with `React.useRef` like in the following example:

```reason
let myTextFieldRef = React.useRef(Js.Nullable.null);

<TextInput
  ref=myTextFieldRef
  // ... more props
 />
```

In this case, the type of `myRef` is `React.Ref.t(Js.Nullable.t(ReactNative.TextInput.element))` and everything works fine.

I therefore find it strange that `forwardRef` takes a `Js.Nullable.t(React.Ref.t('a))` and not a `React.Ref.t(Js.Nullable.t('a))`. Maybe `forwardRef` is typed incorrectly in ReasonReact? What do you think, @MoOx?

**Comment by sgny** [comment]
From the type definitions, it seems to me that you should define the ref beforehand with `useRef`.
```
let ref = React.useRef(Js.Nullable.null);

[@react.component]
let input =
  React.forwardRef((~children, (), ref) => <View ref> children </View>);
```

I simply go with `useRef` and haven't tried `forwardRef`, so please report back if it works. Perhaps `forwardRef` is mistyped, but that is unlikely given [this issue](https://github.com/reasonml/reason-react/issues/421) which suggests `forwardRef` works, but can be improved.

**Comment by jfrolich** [comment]
> I haven't really used `React.forwardRef` yet. I use refs with `React.useRef` like in the following example:
> 
> ```reason
> let myTextFieldRef = React.useRef(Js.Nullable.null);
> 
> <TextInput
>   ref=myTextFieldRef
>   // ... more props
>  />
> ```
> 
> In this case, the type of `myRef` is `React.Ref.t(Js.Nullable.t(ReactNative.TextInput.element))` and everything works fine.
> 
> I therefore find it strange that `forwardRef` takes a `Js.Nullable.t(React.Ref.t('a))` and not a `React.Ref.t(Js.Nullable.t('a))`. Maybe `forwardRef` is typed incorrectly in ReasonReact? What do you think, @MoOx?

Forward refs are a way to forward the ref prop in a component (different than using a ref in a component).

**Comment by jfrolich** [comment]
> From the type definitions, it seems to me that you should define the ref beforehand with `useRef`.
> 
> ```
> let ref = React.useRef(Js.Nullable.null);
> 
> [@react.component]
> let input =
>   React.forwardRef((~children, (), ref) => <View ref> children </View>);
> ```
> 
> I simply go with `useRef` and haven't tried `forwardRef`, so please report back if it works. Perhaps `forwardRef` is mistyped, but that is unlikely given [this issue](https://github.com/reasonml/reason-react/issues/421) which suggests `forwardRef` works, but can be improved.

The idea is to accept a ref prop in a component. The quoted code doesn't do that. You shouldn't need to create a global ref, just a way to pass a an existing ref into a component using the ref prop.

**Comment by sgny** [comment]
Sorry, my bad, I should have checked the React documentation but was too hasty. I remembered one had to use `createRef` (or `useRef`) with `forwardRef` - but forgot that is only when actually using the new component. Apologies.

As @cknitt observed, the signatures for `forwardRef` and `createRef` are mismatched and `forwardRef` seems to be the one that needs to change. I don't know how 

I've created a PR to `reason-react`, but in the meanwhile, you should be able to use the below definition instead

```
[@bs.module "react"]
external forwardRef:
  ([@bs.uncurry] (('props, React.Ref.t(Js.Nullable.t('a))) => React.element)) =>
  React.component('props) =
  "forwardRef";
```

**Comment by jfrolich** [comment]
Yes this actually works. Not sure if reason-react` is typed wrong or `reason-react-native`. Types are a bit strange anyway because to be able to make forwardRef work in React DOM, you have to do some pretty tricky modifications:

```
[@react.component]
let make =
  React.forwardRef((~children, ref) =>
    <div
      ref=?{ref->Js.Nullable.toOption->Belt.Option.map(ReactDOMRe.Ref.domRef)}>
      children
    </div>
  );
```

**Comment by sgny** [comment]
@jfrolich It turns out that there was no mistake with how `forwardRef` was typed. `ref` is typed correctly in these bindings as well.

It wasn't immediately obvious, but if you forget to actually forward a `ref` to the component and call `Ref.current` within that component, then React Native throws an error (red box). Wrapping the `ref` in an `option` is not enough, it actually has to be `Js.Nullable.t`.

```reason
[@react.component]
let input =
  React.forwardRef((~children, (), ref: Ref.t('a)) => 
      ...
      React.Ref.current(ref)
);

works properly if a `ref` is passed, but would cause a red box if no `ref` is passed. One must indeed have

```reason
[@react.component]
let input =
  React.forwardRef((~children, (), ref: Js.Nullable.t(Ref.t('a)) => 
    {
       switch (ref -> Js.Nullable.toOption) {
       | None =>
           <View> children </View> 
       | Some(r) =>
           <View ref=r> children </View>
           React.Ref.current(r)
       }
    }    
);
```

**Comment by MoOx** [comment]
@sgny I guess we can close this issue?

**Comment by sgny** [comment]
Certainly..
