### ISSUE TITLE
Reimplement core deprecated module as new packages (@reason-react-native/*)

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#594]
Ordered by number of download on npm

- [x] https://www.npmjs.com/package/@react-native-community/async-storage (100+k dl/w) [WIP](https://github.com/reasonml-community/reason-react-native/pull/597)
- [x] https://www.npmjs.com/package/@react-native-community/geolocation (15k dl/w)
- [x] https://www.npmjs.com/package/@react-native-community/slider (12k dl/w)
- [x] https://www.npmjs.com/package/react-native-webview (10+k dl/w)
- [ ] https://www.npmjs.com/package/@react-native-community/viewpager (4+k dl/w)
- [ ] https://www.npmjs.com/package/@react-native-community/masked-view (4k dl/w)
- [x] https://www.npmjs.com/package/@react-native-community/checkbox (-1k dl/w)

Another step after that will be famous community packages.

(Note: we could do that now, & integrate the list to priorize on the number of npm download, extracted from core or from the community)

Should we consider at this point to make a dedicated GitHub org `@reason-react-native` and host all packages there?

**Comment by idkjs** [comment]
You know, I think the github org thing might sound more legitimate to some people. If the idea to get more people involved.

**Comment by cknitt** [comment]
Github org sounds good to me! 👍

**Comment by tatchi** [comment]
I would be happy to help with the `async-storage` package :)

**Comment by MoOx** [comment]
@tatchi feel free to open a PR based on netinfo folder, even if it's a WIP :)

**Comment by MoOx** [comment]
I created an https://github.com/reason-react-native, I can create repo when necessary, just ask here for now.
I will split this monorepo asap into multiple packages as (imo) it doesn't make sense now to keep a monorepo as different modules won't need to be in sync with the reason-react-native core repo now that we have something stable.

**Comment by cknitt** [comment]
@MoOx I could contribute:

* https://www.npmjs.com/package/@cca-io/bs-react-native-device-info
* https://www.npmjs.com/package/@cca-io/bs-rn-fetch-blob
* Some stuff that we have not publicly released yet, e.g. react-native-keychain bindings.

Shall we move the core `reason-react-native` repo to the `reason-react-native` org, too?

**Comment by MoOx** [comment]
Nice!

I will extract/move all packages in this monorepo indeed, including the "core" one.

Btw, should do we want to have package named `reason-react-native/*` or do we want to keep `bs-*` for some? Wondering if that's a good idea to have started with `reason-*`... I don't like fragmentations

**Comment by cknitt** [comment]
For me `reason-react-native/*` is fine, so I guess I would rename the above packages to

*  `@reason-react-native/device-info`
*  `@reason-react-native/fetch-blob`

**Comment by MoOx** [comment]
ok I am fine with that. I will start to extract stuff in the next few days.

**Comment by broerjuang** [comment]
Thanks for starting this @MoOx. I would love to contribute on 
- https://www.npmjs.com/package/@react-native-community/slider 
- https://www.npmjs.com/package/@react-native-community/geolocation

**Comment by sgny** [comment]
@MoOx I can work on `WebView`

**Comment by MoOx** [comment]
I created the following repo

- https://github.com/reason-react-native/device-info
- https://github.com/reason-react-native/fetch-blob
- https://github.com/reason-react-native/slider
- https://github.com/reason-react-native/geolocation

Feel free to make PR there!

**Comment by tatchi** [comment]
@MoOx I can help with the `checkbox` one :)

**Comment by MoOx** [comment]
https://github.com/reason-react-native/checkbox

**Comment by cknitt** [comment]
Please also create `keychain`.

BTW, we should standardize the `package.json`s in these projects, especially regarding the scripts (i.e. whether it's `build`, `re:build`, `bs:build` etc.).

**Comment by MoOx** [comment]
Indeed.

https://github.com/reason-react-native/keychain

**Comment by tatchi** [comment]
> Please also create `keychain`.
> 
> BTW, we should standardize the `package.json`s in these projects, especially regarding the scripts (i.e. whether it's `build`, `re:build`, `bs:build` etc.).

Would it make sense to create a [template repository](https://help.github.com/en/articles/creating-a-template-repository) ?

**Comment by cknitt** [comment]
> Would it make sense to create a [template repository](https://help.github.com/en/articles/creating-a-template-repository) ?

Definitely! 👍

**Comment by MoOx** [comment]
I am splitting the monorepo atm.  Will do my best to keep things working, including website, redirections from previous website etc, but might take a day or two, or more :D 
I will make a template asap.
For npm scripts, I would like to keep things simple. What about this

```json
    "start": "bsb -make-world -w",
    "build": "bsb -make-world",
    "test": "bsb -clean-world -make-world"
```

I will propose more commands soon, to handle, auto formatting, releases+tags & stuff like that.
We could discuss that in this repo https://github.com/reason-react-native/__template__

**Comment by MoOx** [comment]
So I copied this repo for all package in it, then removed parts unecessary for each new repo (this was to keep git history).
I will have to flatten all repo as I have kept code in folder as they were. Will do that & will clean things after template is setup & ok on CI :)

**Comment by cknitt** [comment]
> For npm scripts, I would like to keep things simple. What about this
> ...

@MoOx Sounds good! Thanks for all your awesome work! 😃

**Comment by sgny** [comment]
Thanks a lot, the old repo was getting a bit too crowded.

**Comment by wokalski** [comment]
bold & good move with moving the repo to a new org @MoOx.

**Comment by idkjs** [comment]
Bon boulot, @MoOx! Merci!

**Comment by MoOx** [comment]
Btw, I was thinking about renaming the `reason-react-native-template` because if we make a template repo, I don't want things to be confusing & was also thinking that having a template with a more explicit name can help (especially if we imagine having more complex template - spoiler: I plan to make one!)

1. `@reason-react-native/hello-world-template` 👍
1. `@reason-react-native/hello-world` 😄
1. `@reason-react-native/template` 🎉 
1. `@reason-react-native/react-native-template` ❤️ 

Please vote with reactions!

---

[Why hello world? it's what it is...](https://github.com/facebook/react-native/tree/0.61-stable/template/ios)

**Comment by idkjs** [comment]
maybe `@reason-react-native/starter-template`? otherwise 👍

**Comment by MoOx** [comment]
starter seems ≃ to template to me, so
we could add

- `@reason-react-native/hello-world-starter`
- `@reason-react-native/starter`

Personally not a fan of "starter" naming tho.

**Comment by idkjs** [comment]
If the idea is to say hey, use this to get started and being explicit, the name should suggest that. So how about `@reason-react-native/use-this-to-get-started-template` which is bad, but you understand what I mean. The others say, "Hey, look at this. It works". Maybe just be sure to put a `template` tag on the repo and mention it in the docs. This is officially bikeshedding so I will stop now.

**Comment by MoOx** [comment]
Now that we simplified main repo, if you are ok with current structure of https://github.com/reason-react-native/reason-react-native, I could make a template repo for all bindings (!= react native template) so we can move forward with it (we might have to update CONTRIBUTING.md to add more technical details but we can do that later).

**Comment by MoOx** [comment]
(I focused on the main repo so it's back on track, will handle others repo & new repo/PRs asap)

**Comment by MoOx** [comment]
Thoughts on this template? https://github.com/reason-react-native/__template__/pull/1

**Comment by idkjs** [comment]
Something to start with. Guess you got tired of repeating that process. You will get some feedback when you put it out there.

**Comment by sgny** [comment]
I have just added bindings for [`datetimepicker`](https://github.com/react-native-community/react-native-datetimepicker/). Apparently, `DatePickerIOS`, `DatePickerAndroid` and `TimePickerAndroid` have been merged, but while they still remain included, the new component has already been ejected.

**Comment by sgny** [comment]
I think it's time we started deprecating/removing some of these modules as most of these components/APIs no longer exist.

However, to allow people to use older versions of RN, we can simply remove what has been deprecated or removed until some reasonable version and deprecate everything else deprecated or removed since then.

Therefore, we should decide what is reasonable. To remind everyone here are the release dates for recent RN versions (initial release and final minor release):

| Version  | Release date  |
|---|:-:|
| 0.59  | March 12, 2019  |
| 0.59.10  | July 2, 2019  |
| 0.60  | July 3, 2019  |
| 0.60.6  | September 24, 2019  |
| 0.61  | August 27, 2019 |
| 0.61.5  | November 23, 2019 |

I think anything that's been removed since v 0.60 should at least be marked as deprecated.

**Comment by MoOx** [comment]
>  to allow people to use older versions of RN

People can just use older bindings right?

I think it's time to release a clean slate & remove everything that has been deprecated & removed. Most moved repo have their own bindings now.

**Comment by sgny** [comment]
Sure. In fact, I think at this stage, anyone using older versions of RN should be better off using the community version of what are probably long neglected components.

- Should we remove everything at once or one PR per removed module?
- Should we update documentation to inform of the removal and point towards the replacement?

**Comment by MoOx** [comment]
To make this simple

- Yes
- Yes but just link to new pages => we should add docs for all existing module in the rrn org. I will try to work on that so search field could give result if you look for "navigation", "netinfo" etc...

So we could first remove all & keep md with just a link inside to repo, I will replace those link to rrn repos in an upcoming PR in the website.

**Comment by sgny** [comment]
Below is a recap of what's been deprecated or removed. * indicates new bindings already available (`AlertIOS` is replaced by `Alert`).

**Deprecated**

| Module  |   |
|---|:-:|
| AsyncStorage  | * |
| Clipboard  | * |
| CheckBox | * |
| DatePickerAndroid | * |
| DatePickerIOS | * |
| ImagePickerIOS | * |
| MaskedViewIOS | |
| Picker | |
| PickerIOS | |
| ProgressBarAndroid | |
| ProgressViewIOS | |
| PushNotificationIOS | * |
| SegmentedControlIOS | |
| Slider | * |

**Removed**
| Module  |   |
|---|:-:|
| AlertIOS | * |
| CameraRoll | |
| GeoLocation | |
| ImageEditor | |
| NetInfo | * |
| TimePickerAndroid | * |
| ToolbarAndroid | |
| ViewPagerAndroid | * |
| WebView | * |


We do not have bindings for appropriate replacements of quite a few components/APIs. I intend to add a few more (`CameraRoll`, `ImageEditor` and perhaps few more), but I expect we still will miss a few of them.

When we **do not** have such bindings
• I believe it makes sense to express in their documentation that they are deprecated and will be removed in the future but not yet remove them.
• should we trigger deprecation warnings?
• should we add a repo for each replacement and point towards that even if we don't yet have the bindings?

When we **do** have such bindings
• should we remove them?
• should we keep them and trigger deprecation warnings?

**Comment by MoOx** [comment]
I would do:

For deprecated: nothing, as RN already pops an alert during development. People should already looks for alternative.

If we don't have bindings for alternative, well we don't have them! It's the time to work on it (I am not saying you or I should handle it). People can contribute back or just come and express their need & help to handle some new bindings.

For removed: just remove them. As I said before, I think if a thing is removed from 0.x from RN, bindings at 0.x should just remove them. No warning or nothing except notes in the changelog.

**Comment by sgny** [comment]
Now that some of these components have been removed from React Native, name space conflicts are no longer an issue. Accordingly, couldn't we simplify names of some of the new modules? For example, instead of `ReactNativeWebView`, we could switch back to `WebView`.

**Comment by MoOx** [comment]
I am just afraid that with this, we could have clash for generic name. What if another ocaml/reasonml thing have the same generic name (eg: Location) ? That's the main reason I will stick to ReactNativeXxxxx. Otherwise if that's really a problem, we cold adhere to native naming like RN community is doing for Podspec & friends RNXxxx ?

**Comment by MoOx** [comment]
I have the feeling that most used modules have been shipped already into the org. Feel free to continue to ask more repo if you want to push some bindings :)
