### ISSUE TITLE
Add missing Animated.FlatList & SectionList

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#599]
https://github.com/reasonml-community/reason-react-native/blob/1bbb716dff888ad67b06641c67a31aa3e01f7c49/reason-react-native/src/apis/Animated.re#L284-L306

vs

https://github.com/facebook/react-native/blob/adac04601ec36d35eca42532ec824c5790dc71ed/Libraries/Animated/src/Animated.js#L23-L40

**Comment by sgny** [comment]
Please comment on #600.
