### ISSUE TITLE
SectionList classic RN example is impossible with current typings

### ISSUE THREAD

**Issue by elnygren** [reason-react-native/reason-react-native#605]
The following example is a bit hard to pull off with ReasonML, making SectionList quite awkward to use:

https://facebook.github.io/react-native/docs/sectionlist.html
```
// Example 1 (Homogeneous Rendering)
<SectionList
  renderItem={({item, index, section}) => <Text key={index}>{item}</Text>}
  renderSectionHeader={({section: {title}}) => (
    <Text style={{fontWeight: 'bold'}}>{title}</Text>
  )}
  sections={[
    {title: 'Title1', data: ['item1', 'item2']},
    {title: 'Title2', data: ['item3', 'item4']},
    {title: 'Title3', data: ['item5', 'item6']},
  ]}
  keyExtractor={(item, index) => item + index}
/>
```

The problem is that it's not possible to put "title" or other custom fields into `sections`. However, practical usecases of SectionList do require that you're able to access custom datapoints in `renderSectionHeader` that are part of the sections (imagine if each section has a larger Js.t object for each SectionHeader, not just title string...).

**Comment by MoOx** [comment]
Here we use a non defined type https://github.com/reason-react-native/reason-react-native/blob/c7a691cb9f21f962e5c0e4298607944f634f5ee9/reason-react-native/src/components/SectionList.re#L25

If you define your own type somewhere, inference should work. Did you tried that?

**Comment by elnygren** [comment]
The problem is that `section('item)` doesn't allow customising other than the item in the "data"-array.

https://github.com/reason-react-native/reason-react-native/blob/e93b88aeffc3b000492367d2ac85114a0e64b438/reason-react-native/src/components/VirtualizedSectionList.re#L14-L22

In order to do what the official RN example shows, the type of section itself should be more flexible.

I'm not 100% sure but could using two dots here help?

```
section('item) = { 
   .. // <- add another one to allow extra fields...
   "data": array('item), 
   "key": option(string), 
   "renderItem": option(renderItemCallback('item)), 
   "ItemSeparatorComponent": option(unit => React.element), 
   "keyExtractor": option(('item, int) => string), 
 } 
```

**Comment by MoOx** [comment]
I never heard about this `..`. Can you try modifying the code in your node_modules to see if this help?

**Comment by elnygren** [comment]
https://reasonml.github.io/docs/en/object#type-declaration

> Two dots, also called an elision, indicate that this is an "open" object type, and therefore can also contain other values and methods. An open object is also polymorphic and therefore requires a parameter.

It seems to work with Js.t objects too, although probably not as easily as I showed :/ 

https://reasonml.github.io/try?rrjsx=true&reason=C4TwDgpgBA9pB2ApAygCgOQEMCUUC8UA3gFBQB0ZpARDPBAGICWEANgCZUBcUj8wANFGIBfKJgDOULAG5ixFhGBQAZjBjc4EJGiy4CJKFBp0mrDtwCMAJgDM-UkYgAPYACdMp9lyg2rF+8LSQA

**Comment by sgny** [comment]
@elnygren I hadn't noticed `..` either, thanks for bringing it to our attention. Also, it isn't obvious from the documentation of `SectionList` that one could have additional keys in the object; thank you for the example as well.

@cknitt Types such as `section('item)` need to be created, shouldn't they be defined using `[@bs.obj]`? However, then, we can no longer use `..`

**Comment by cknitt** [comment]
@sgny Yes, according to our conventions we would use `[@bs.obj]` for creating section objects to pass to `SectionList`. But then the user cannot add arbitrary keys in the section objects like with the `..` trick.

What we could maybe do though is something like

```reason
[@bs.obj]
external section:
  (
    ~data: array('item),
    ~key: string=?,
    ~renderItem: renderItemCallback('item)=?,
    ~_ItemSeparatorComponent: unit => React.element=?,
    ~keyExtractor: ('item, int) => string=?,
    ~extraData: 'extraData=?,
    unit
  ) =>
  t =
  "";
```

to allow the user to pass one fixed additional field `extraData` which contains any Reason record / JS obj the user wants.

**Comment by sgny** [comment]
> @sgny Yes, according to our conventions we would use `[@bs.obj]` for creating section objects to pass to `SectionList`. But then the user cannot add arbitrary keys in the section objects like with the `..` trick.
> 
> What we could maybe do though is something like
> 
> ```reason
> type section;
> 
> [@bs.obj]
> external section:
>   (
>     ~data: array('item),
>     ~key: string=?,
>     ~renderItem: renderItemCallback('item)=?,
>     ~_ItemSeparatorComponent: unit => React.element=?,
>     ~keyExtractor: ('item, int) => string=?,
>     ~extraData: 'extraData=?,
>     unit
>   ) =>
>   section =
>   "";
> ```
> 
> to allow the user to pass one fixed additional field `extraData` which contains any Reason record / JS obj the user wants.

Yes, that's how I thought one could do it. It's a bit of a restriction compared to what `..` allows; not that there is anything actually lost by the restriction.

So should we revise for consistency then?

**Comment by MoOx** [comment]
`~extraData: 'extraData=?` seems a good tradeoff

**Comment by cknitt** [comment]
Yes, I think we should revise for consistency.

**Comment by MoOx** [comment]
@elnygren would you be open to help us handle this and propose the change as we discussed in a PR? Or anyone interested in helping us?

**Comment by sgny** [comment]
@MoOx I'll get started on this

**Comment by sgny** [comment]
See #614
