### ISSUE TITLE
Exposing global.HermesInternal

### ISSUE THREAD

**Issue by sgny** [reason-react-native/reason-react-native#610]
As of RN 0.60, Hermes JS engine can be used on Android. To check whether that engine is enabled, RN provides the `global.HermesInternal` variable which could/should go in `Global` (name pending further discussion) along with `__DEV__`. 

However, adding proper bindings is a bit non-sensical. What you have is a variable which has the value `undefined` when Hermes is disabled and `{}` when enabled (really!).

So the bindings can be either
```reason
module Hermes = {
	type t;

	[@bs.val] [@bs.scope "global"]
	external status: t = "HermesInternal";

	external disabled : unit => t = "#undefined"
	[@bs.obj] external enabled: unit => t = "";
};
```
using the established way to create an empty object, as used on `Js.Dict.empty()`, etc. In use, one might have
```reason
Hermes.status == Hermes.enabled()
```
such a function call may be avoided as below 
```reason
module Hermes = {
	type t;

	[@bs.val]
	external status: t = "HermesInternal";

	external disabled : t = "#undefined"
	[@bs.val]
	external enabled: ([@bs.as {json|{}|json}] _) => t =
  "Object.assign";
};
```
which would be used as
```reason
Hermes.status == Hermes.enabled
```
The latter introduces a bit of noise due to `Object.assign` on the JS side.

IMO, it's better to simply add a function (not zero-cost, _per se_ but that cost would be incurred at the call site anyway) as below
```reason
let (isHermesEnabled: bool) = [%bs.raw {| global.HermesInternal != null |}];
```
(it really should be compared to `undefined`, but perhaps following documentation may be more future proof).

Any opinions?

**Comment by MoOx** [comment]
What about something zero cost based on an `option`? Since option are encoded `undefined | {something}` this would work if you do `Global.hermesInternal->Belt.Option.isSome()`?
With the proper doc, should be acceptable & safe?

**Comment by sgny** [comment]
That's reasonable. I wanted something that would not need any documentation, but perhaps we could simply suggest
```reason
Global.hermesInternal != None
```
which feels quite similar to what is recommended on the JS side.
