### ISSUE TITLE
No easy way to read from a Style.t value (using StyleSheet.flatten)

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#619]
## The problem

We currently don't have an easy way to read style values.

## Considered solution

Adding an external to pass from `Style.t` to a raw JS object or json.

## Alternatives solutions

Code the object with all possible keys, but that can be a lot.

## Additional context

Standard RN [StyleSheet.flatten](https://facebook.github.io/react-native/docs/stylesheet#flatten) returns a raw js style object that you can read from.
Our abstract type `Style.t` doesn't allow this atm & our StyleSheet flatten method takes an array of Style.t & returns a Style.t.

**Comment by sgny** [comment]
I think a neat solution is quite established by now. Whenever we have a type that needs to be created as well as consumed, we add a constructor using `@bs.obj` as well as a type definition as a `Js.t` object. This way `##` accessors can be used as usual.

If that seems reasonable, I'll fashion a PR.

**Comment by MoOx** [comment]
Problem is that StyleSheet.create returns a map of ids (int) that are resolved by the style props of all components. We have to keep in mind that RN "styles" can be int | {string: 'value}... So we can't just do that that easily. Maybe we could make a method that can raise an error in case reading the object value fails? Because StyleSheet.flatten actually returns an object so maybe we should change this? And if people want to use this, they can use it as unsafe styles?!

**Comment by sgny** [comment]
@MoOx I'm surprised this did not actually work, because I have been using similar implementations elsewhere with no problem.

I have already prepared a WIP PR (#622) with an alternative approach. That does indeed work 😁

**Comment by MoOx** [comment]
This issue is an edge case and it seems very few people are looking for this.
Can be handled in user land.

In case you aren't sure, we can still continue discussion here.
