### ISSUE TITLE
RFC for array styles zero-cost method

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#632]
## The problem

It's a bit _too_ verbose to write `Style.(array([| style1, style2 |]))`. This solution is nice, especially for zero-cost, but I have found something useful that might be added here.

## Considered solution

Tuples are encoded as array by bucklescript. We could leverage this by adding methods similar to this:

```re
external _2: (('a, 'a)) => 'a = "%identity";
external _3: (('a, 'a, 'a)) => 'a = "%identity";
external _4: (('a, 'a, 'a, 'a)) => 'a = "%identity";
external _5: (('a, 'a, 'a, 'a)) => 'a = "%identity";
external _6: (('a, 'a, 'a, 'a, 'a)) => 'a = "%identity";

external _2options: ((option('a), option('a))) => 'a = "%identity";
external _3options: ((option('a), option('a), option('a))) => 'a = "%identity";
external _4options: ((option('a), option('a), option('a), option('a))) => 'a = "%identity";
external _5options: ((option('a), option('a), option('a), option('a))) => 'a = "%identity";
external _6options: ((option('a), option('a), option('a), option('a), option('a))) => 'a = "%identity";
```

This might help to replace

```re
Style.array([| style1, style2 |])
```

by

```re
Style._2(style1, style2)
``` 

Open to ideas for the naming. I would like to something short since it's the purpose of this new methods :D 

## Alternatives solutions

More Ideas?

**Comment by cem2ran** [comment]
I have started opening `Style` by default in all component related files and find this to be sufficient for me. `_2`, `_3`, etc, would need explicit documentation thus wouldn't be idiomatic which I would prefer any day. 

Just to compare to the above two examples I now do the following:

```
open Style; //either in toplevel of file or inside make.

array([| style1, style2 |])
```

If you don't open Style which probably most people don't then you could maybe override either the array or list operator:

```
Style.[style1, style2]
```

Sketch.sh pseudo code: https://sketch.sh/s/N4IZ22mapgfz1TwATidolh/

An operator to combine style could probably also work:

```
style1 + style2
```

**Comment by MoOx** [comment]
@cem2ran Thanks for this precious feedback. That's more than interesting!
I don't think enough sometimes & the naming of methods I am offering definitely sucks!

The override and/or operator thing is a cool idea!

Let's wait for more comments/ideas :)

**Comment by jfrolich** [comment]
Personally I think the current state is fine. This just adds more API surface for not too much gain. I usually do  `Style.(style(...))` anyway, so it's  just `array([|...|])`.

**Comment by MoOx** [comment]
That's less a problem with .res syntax.
