### ISSUE TITLE
React Native TextInput autoCompleteType is named here autoComplete

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#634]
[A prop named `autoCompleteType` for TextInput](https://facebook.github.io/react-native/docs/textinput#autocompletetype) is named in this bindings `autoComplete`

@cknitt it seems to comes from original bindings you pushed in https://github.com/reason-react-native/reason-react-native/pull/352

Is this on purpose? Is there any reason?

**Comment by cknitt** [comment]
@MoOx I don't remember any special reason for this. I guess it's just a bug in the original bindings. Thanks for the catch!
