### ISSUE TITLE
Animated component refs do not point to the component

### ISSUE THREAD

**Issue by benadamstyles** [reason-react-native/reason-react-native#643]
## The problem

Refs, when set from animated components (e.g. `Animated.FlatList`), are incorrectly typed. In React Native, the refs for these `Animated` components have a `_component` property which points to the actual component. This is not accounted for in the Reason React Native types, so if you call a method on a ref, your app crashes.

### How to reproduce

```reason
let make = () => {
  let flatListRef = React.useRef(Js.Nullable.null);

  <>
    <Animated.FlatList
      ref=flatListRef
      data={[||]}
      keyExtractor={(_item, index) => index->string_of_int}
      renderItem={props => <View />}
    />
    <TouchableOpacity
      onPress={_ =>
        flatListRef
        ->React.Ref.current
        ->Js.toOption
        ->Belt.Option.forEach(flatList =>
            Animated.FlatList.(
              flatList
              ->scrollToOffset(
                  scrollToOffsetParams(
                    ~offset=Device.screenWidth,
                    ~animated=true,
                    (),
                  ),
                )
            )
          );
      }
    />
  </>;
};
```

## Expected behavior

This code is type-correct, so tapping the button should not throw.

## Actual behavior

App crashes with `scrollToOffset is not defined` or similar. This is because on `Animated` components, `ref`s should point to a property on the ref called `_component`.

## Additional context

I have tried to make a PR to fix this but I need some advice – the way refs are set up for these `Animated` components, using [`VirtualizedListElement.re`](https://github.com/reason-react-native/reason-react-native/blob/master/src/elements/VirtualizedListElement.re), makes it very complicated for me to understand how we could customize the `ref` prop for just these components.

**Comment by MoOx** [comment]
Maybe the way we currently define animated components isn't the best thing we can do as ref is by definition wrong (otherwise you would not have faced a runtime error).

Maybe it's time to stop avoiding some copy/paste & make "standard" bindings for `Animated.*` with adjustment for ref. 
We could offer an `Animated._component` accessor (or a better name) so people can do normal ref access like they do with normal RN.

What do you think? 

Poke @cknitt @sgny

**Comment by sgny** [comment]
@benadamstyles @MoOx 

I think we can handle this rather easily if I have the right notion. I'll quickly put together a PR if it works.

@MoOx No need to start copy/pasting just yet. `createAnimatedComponent` wraps these components, so we need to access the actual component if we want to use any relevant methods.

**Comment by sgny** [comment]
It seems this will be fixed in 0.62 according to this [commit](https://github.com/facebook/react-native/commit/66e72bb4e00aafbcb9f450ed5db261d98f99f82a).

At least for a while, `getNode` will still work but throw an error. So, should we

• wait for 0.62, change nothing in the bindings and simply add a note to the README explaining how to handle this?
• add a solution and remove it later when `getNode` is removed altogether (then the app will keep throwing errors)?
• add a solution and remove it later when 0.62 shows up?

**Comment by MoOx** [comment]
> so we need to access the actual component if we want to use any relevant methods.

But this means that we need to change the type of ref so we can give the correct type so we can call correct method without too much Obj.magic

Not sure we can wait 0.62 as you cannot generally rush on releases... If we could make a quick patch that would be nice. I think we could go for adding getNode somehow & remove it in 0.63+ (so people can upgrade to 0.62 + see deprecation notice & remove it totally when RN remove it for good)

How do you think we can provide getNode() to say "take this "animated ref" and give the real ref" ?

**Comment by sgny** [comment]
With OCaml >=4.08, we would be able to override types while importing modules, so we could simply do that but as BS is based on 4.02 or 4.06 we canot. On the other hand, this does not add any actual costs on the JS side and should be temporary anyway.

**Comment by MoOx** [comment]
@benadamstyles did you find any workaround that's acceptable?
The change to accept this, that would only be needed until RN 0.62 is out, is quite big.
See #644

**Comment by benadamstyles** [comment]
Hi @MoOx, thanks for checking in, I worked around it like this:

```reason
let hackFixAnimatedRef =
    (el: Animated.FlatList.element): Animated.FlatList.element =>
  Obj.magic(el)##_component;
```

I'm happy to leave it like this until the next version, feel free to close this issue if you prefer. It will be useful for other users who might hit this problem though!

**Comment by MoOx** [comment]
I guess this issue isn't relevant now that 0.62 & 0.63 are out (with bindings).
