### ISSUE TITLE
allow `href` on Text for react-native-web 

### ISSUE THREAD

**Issue by jfrolich** [reason-react-native/reason-react-native#649]
In combination with `accessibilityRole=`link` (already implemented) allows you to do links in RNW.

**Comment by jfrolich** [comment]
Perhaps also good to look at other properties that only apply to web:
https://github.com/necolas/react-native-web/blob/5b7f584f191d8fb6e5c92fa560c4e6babca7559f/packages/react-native-web/src/exports/View/filterSupportedProps.js#L52-L76.

**Comment by MoOx** [comment]
We could add support for that, but I would like to know how "unstable" some web only are (are they going to be removed at some point?) poke @necolas

**Comment by necolas** [comment]
It will probably change in the future but not sure when. The problem with the current RN API is you can easily create interactive text that a web browser won't see as a URL and a user can't interact with as a link (e.g., `<Text onPress={onPress} />`). So making it intentionally difficult to create this kind of inaccessible pattern should be a design goal in the future

**Comment by MoOx** [comment]
Done in #650
We can revisit and remove stuff later if needed.
