### ISSUE TITLE
Could not create a new app with cli template.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reason-react-native/reason-react-native#651]
## The problem

```
 npx @react-native-community/cli init --template @reason-react-native/template 
```

### How to reproduce

Steps to reproduce:

1. `npx @react-native-community/cli init --template @reason-react-native/template  App`

## Expected behavior

An app with reasonml has to be generated.

## Actual behavior

Error
```
npm ERR! Unexpected end of JSON input while parsing near '...694+ZW1QWXWVftSGVTjim'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/a-c-sreedhar-reddy/.npm/_logs/2020-03-26T15_36_21_099Z-debug.log
Install for @react-native-community/cli@latest failed with code 1

```

![Screenshot from 2020-03-26 21-28-15](https://user-images.githubusercontent.com/16081083/77668557-90ef9d00-6fa9-11ea-830c-e1f9d1d0b0f3.png)
* OS - Ubuntu 18.04.4 LTS
* `node -v` - v10.16.3
* `npm -v` - 6.13.0

**Comment by a-c-sreedhar-reddy** [comment]
https://github.com/react-native-community/cli/issues/1074#issuecomment-604506823

**Comment by a-c-sreedhar-reddy** [comment]
https://github.com/react-native-community/cli/issues/1074#issuecomment-604506823

**Comment by MoOx** [comment]
Please provide additional detail like
- os
- node version
- npm version

**Comment by MoOx** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/157534/77666888-ced8cb00-6f81-11ea-9311-7938f42c42ff.png">

**Comment by a-c-sreedhar-reddy** [comment]
![Screenshot from 2020-03-26 21-28-15](https://user-images.githubusercontent.com/16081083/77667882-c34cca80-6fa8-11ea-8c9e-e6b557c8afcd.png)
* OS - Ubuntu 18.04.4 LTS
* `node -v` - v10.16.3
*`npm -v` - 6.13.0

**Comment by MoOx** [comment]
Please reset your npm cache & try again.
It's definitely not a reason-react-native issue.
