### ISSUE TITLE
0.62 bindings

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#653]
https://reactnative.dev/blog/2020/03/26/version-0.62

Is anyone working on this?

(@sgny I suspect you do since you worked with the repo recently)

**Comment by sgny** [comment]
@MoOx :grin: Yes, I'll be pushing a few PRs.

**Comment by MoOx** [comment]
@sgny thanks for handling this!
I would like to wait for #666 before cutting a new release, what do you think?

**Comment by sgny** [comment]
A pleasure.

Are you aware of any issue migrating from v5 to v7? I'm not aware of any showstoppers, so I trust we are ready to move to v7. Then, we should include #666. I suppose we will not have another release for a while yet.

**Comment by MoOx** [comment]
I didn't get any on small projects I handle. Just a few things some dependencies but bumping & fixing in issues in the dependencies was easy.
I think it's time to try v7 yeah. Worst case scenario: we cut a release without this PR :) (named for example 0.62.0-bs5)

**Comment by sgny** [comment]
I only got around to preparing the PR to remove outdated modules. Should we use this opportunity to move contents of `Global` into `DevSettings`?

**Comment by MoOx** [comment]
We have `__DEV__` which could make sense & `hermesInternal` not sure if this one fit here.
And since Global is shorter than DevSettings, we could keep this 2 bindings where they are.

What do other people think?

**Comment by MoOx** [comment]
I have to finish some updates for the website & we should be good I think

**Comment by MoOx** [comment]
OK website is ready-ish (I want him to use RRN 0.62 :) ) but if everything is good, we can cut a release. I can prepare changelog and handle that if everybody is ok with that. @sgny 'r you ok with this?

**Comment by MoOx** [comment]
FYI, I will enhance the website so we can have the source if `wip: true` is in the md header so we don't have to maintain this by hand until real docs are a thing :D

**Comment by sgny** [comment]
@MoOx I would like to take a quick look at #604 to see if we can close that issue with this release. Would you mind holding the release for a day or two?

**Comment by MoOx** [comment]
Yeah no problem. Thanks for all the hard work!

**Comment by sgny** [comment]
This is an interim report. It turns out that what methods are available for any given component is rather complicated. I have reviewed `FlatList`, `ScrollView`, `SectionList`, `VirtualizedSectionList` and `VirtualizedList` to determine methods available for each and will proceed to prepare a comprehensive PR.

**Comment by sgny** [comment]
I prepared PR #680 to remove methods, but not yet introduced some methods that I realised were omitted.

**Comment by MoOx** [comment]
reason-react 0.8 is about to go out, it would be nice to wait for the release as well.

**Comment by MoOx** [comment]
I have prepared migration for all packages but waiting for us to release the 0.62 bindings.
I have 2 questions:
- do we upgrade to reason-react 0.9 ? (I see not real breaking changes)
- what solution do we choose for events (see all pending PRs)

cc @sgny @cknitt & friends :)

**Comment by MoOx** [comment]
(meanwhile, I am preparing release notes)

**Comment by MoOx** [comment]
0.62 is out. Thanks for everyone involved and especially @sgny !
Will try to update the website soon (probably by the end of the week)
