### ISSUE TITLE
 Using react-native-keyevent library does not work

### ISSUE THREAD

**Issue by wontheone1** [reason-react-native/reason-react-native#671]
## The problem

I am developing for a handheld android laser barcode scanner. I need to use [this library](https://github.com/kevinejohn/react-native-keyevent/tree/844256c41ea16b908cc6df0dedde956d06678a87) (since laser barcode scanning is external keyboard key events I believe). Since UI requirement is that I should not display the software keyboard on screen I need to listen to external keyboard key events.

To make sure I did all the configuration steps from the library correctly, I tried using it from React Native project and it worked. But could not transport it to Reason React Native project.

### How to reproduce

Steps to reproduce:

1. Install react-native-keyevent library and do what [Configuration](https://github.com/kevinejohn/react-native-keyevent/tree/844256c41ea16b908cc6df0dedde956d06678a87#configuration) section says (I only did it for Android)

2. Make externals.
```
[@bs.module "react-native-keyevent"]
external onKeyMultipleListener:
  ([@bs.uncurry] (ReactEvent.Keyboard.t => unit)) => unit =
  "onKeyMultipleListener";

[@bs.module "react-native-keyevent"]
external onKeyDownListener:
  ([@bs.uncurry] (ReactEvent.Keyboard.t => unit)) => unit =
  "onKeyDownListener";

[@bs.module "react-native-keyevent"]
external keyevent: ([@bs.uncurry] (ReactEvent.Keyboard.t => unit)) => unit =
  "default";
```

3. Try to use one of the externals such as `onKeyDownListener`. (I used js interop to make sure the exact same code that works for React Native app. (and `ReactNativeKeyevent` is the module alias of compiled `App.bs.js` file.
```
  %bs.raw
  {| ReactNativeKeyevent.onKeyDownListener((keyEvent) => {
      console.log(`onKeyDown keyCode: ${keyEvent.keyCode}`);
      console.log(`Action: ${keyEvent.action}`);
      console.log(`Key: ${keyEvent.pressedKey}`);
    }) |};
```

## Expected behavior

On step 4, instead of a runtime error, it should trigger the event handler, `onKeyDownListener` and see the console log messages.

## Actual behavior

Runtime error occurs because `onKeyDownListener` is undefined.
<img width="383" alt="Screen Shot 2020-04-11 at 7 03 00" src="https://user-images.githubusercontent.com/11784756/79035294-c27d8080-7bc5-11ea-8c91-07d5bf1ab9ca.png">

## Environment

I am developing on Mac. Following is my package.json dependencies
```
  "dependencies": {
    "react": "^16.9.0",
    "react-native": "^0.61.0",
    "react-native-keyevent": "^0.2.7",
    "react-native-paper": "^3.8.0",
    "react-native-vector-icons": "^6.6.0",
    "reason-react": "^0.7.0",
    "reason-react-native": "^0.61.0"
  },
```

## Additional context

I pushed my entire project to public Github + made a pull request of the commit where I think is the minimal change that produces the problem. Please refer there to have more context.

All the things you do are much appreciated!

Repo: https://github.com/wontheone1/reasonmldebugging
Pull request: https://github.com/wontheone1/reasonmldebugging/pull/3

**Comment by sgny** [comment]
`@bs.raw` is only for JS code in Reason/OCaml code. Your external definitions would have no information on the bindings, hence no JS code to call within `@bs.raw` block.

**Comment by sgny** [comment]
I figured since I worked out what was wrong with these, I might as well publish them. Please checkout the resultant [bindings](https://www.npmjs.com/package/reason-react-native-keyevent).
```
yarn add reason-react-native-keyevent
```

**Comment by wontheone1** [comment]
As @sgny pointed out, external definitions are wrong and the right one is found in https://github.com/sgny/reason-react-native-keyevent

Closing issue!
Thank you for the help!
