### ISSUE TITLE
Discussion about Style.size public type

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#679]
I am currently working on svg bindings, they should be good. In lots of place, Style.size is used.
That said, for convenient, when working with lots of SVGs, converted from string svg, it's a pain to convert all props.

This would be a lot easier if Style.size was publicly a string.

So I know why we did the choice in the first place to have string only internal, to force people using dp/pct units to benefit from strong types... But at the end, it can be counter productive at some point.

So what do you think about adjusting `size` to be publicly a `string`?

We can decide to do that & don't communicate on this (to encourage people to use units function) or we could decide to do like reason-react & be gentle about some stuff, with the risk of having runtime errors.

**Comment by sgny** [comment]
I'm probably missing something, but what's the issue with simply setting `type size=string` only for `ReactNativeSvg`?

I do prefer preventing runtime errors as much as possible, but in order not to introduce a possibly unnecessary dependency, for `GeoJson` support in [`reason-react-native-maps`](https://github.com/sgny/reason-react-native-maps/blob/master/src/Geojson.re) I simply let the user determine the type. We could have a similar setup for SVG where you have an unsafe version where `size = string`. We could do the same for `Style` in this module if both types needs to be the same.

**Comment by MoOx** [comment]
You are right. Anyway since I opened this issue, I added conversion from my tool https://github.com/MoOx/react-from-svg/blob/14fb0f1bb32fda88d6e3d847319037353e4aa6c6/src/AdjustSvg.re#L135-L148
