### ISSUE TITLE
Compilation failure with reducerComponent - ReasonReact.componentSpec(blah, blah..)     vs     React.element

### ISSUE THREAD

**Issue by alltonp** [reason-react-native/reason-react-native#683]
Hi,

Firstly thank you for the reason-react-native, I'm just starting out with it and so far it's been an enjoyable experience.

I'm new to Reason, React and Native, so apologies if this is a stupid question! I'm having trouble trying to use a reducerComponent and getting the following error:

```
1 │ /* App.re */
2 │ open ReactNative;
3 │ let app = () => <View> <Switcheroo /> </View>;

This has type:
    'a =>
    ReasonReact.componentSpec(Switcheroo.state, Switcheroo.state,
                               ReasonReact.noRetainedProps,
                               ReasonReact.noRetainedProps, Switcheroo.action)
  But somewhere wanted:
    React.component('a) (defined as 'a => React.element)
  
  The incompatible parts:
    ReasonReact.componentSpec(Switcheroo.state, Switcheroo.state,
                               ReasonReact.noRetainedProps,
                               ReasonReact.noRetainedProps, Switcheroo.action)
    vs
    React.element
  
FAILED: subcommand failed.
```

This was generated by the following code:
```
/* Switcheroo.re */
open ReactNative;

type state = {toggled: bool};

type action =
  | SetSwitchValue(bool);

let component = ReasonReact.reducerComponent("Switcheroo");

let make = _children => {
  ...component,
  initialState: () => {toggled: false},
  reducer: (action, _state) =>
    switch (action) {
    | SetSwitchValue(v) => ReasonReact.Update({toggled: v})
    },
  render: self =>
    <Switch
      value={self.state.toggled}
      onValueChange={value => self.send(SetSwitchValue(value))}
    />,
};

/* App.re */
open ReactNative;
let app = () => <View> <Switcheroo /> </View>;
```

Using:
```
  "dependencies": {
    "react": "^16.9.0",
    "react-native": "^0.61.0",
    "reason-react": "^0.7.0",
    "reason-react-native": "^0.61.0"
  },
```

FYI, that code came from here https://medium.com/@FiberJW/persistence-in-reasonml-react-native-apps-55d72a8c9e4c which looks like it uses an older version, so I had to alter it a bit.

Where am I going wrong? 

Also are there any other examples of using reducerComponent with reason-react-native? This was the only one I could find. I'm coming from Elm and the reducer style looks pretty close to how Elm works, so would really like to use it.

Many thanks,
Paul

**Comment by sgny** [comment]
`ReasonReact` is the old API, without hooks and a lot more compilation artifacts. There are a few examples utilising reducers (`useReducer` hook) in this repo, but if you still like the older API, see [`reason-react-update`](https://github.com/bloodyowl/reason-react-update).

**Comment by MoOx** [comment]
I would add that you can safely refer to ReasonReact docs (Examples section) for this https://reasonml.github.io/reason-react/docs/en/usereducer-hook.

**Comment by MoOx** [comment]
Note: it's exactly the same for ReasonReactNative which rely on ReasonReact.

ReasonReactNative is just a bunch of bindings for ReactNative APIs & Components so for purely React bindings, ReasonReact is the reference.

Try our Discord #react-native channel if you have more questions https://reason-react-native.github.io/reason-react-native/discord/

**Comment by alltonp** [comment]
Thank you both, managed to get it working with the use reducer hook.

**Comment by alltonp** [comment]
MoOx thank you also for your YouTube videos, they were very helpful for getting started with reason-react-native
