### ISSUE TITLE
Revisit some syntheticEvent/responderSyntheticEvent (eg: e->preventDefault)

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#688]
Following https://github.com/reason-react-native/reason-react-native/pull/681

@sgny said

> `e->preventDefault`, etc. are what's available with `reason-react`, so we may as well implement that while we're breaking things. 
>
> `reason-react`'s `MakeEventWithType` is more consistent with using `@bs.get/@bs.send` methods to access keys, but I think our approach in keeping the record for all non-method keys is more straightforward. I suppose the slight inconsistency is quite alright.
>
> How do we handle the `syntheticEvent` and `responderSyntheticEvent` difference when it comes to the methods however? Should we namespace one or the other or functorise all these event types instead?

**Comment by sgny** [comment]
I'm working on this with two alternatives. I'll present them for feedback soon, hopefully later tonight.

**Comment by MoOx** [comment]
Closed by #695
