### ISSUE TITLE
Use [@bs.unwrap] for transforms

### ISSUE THREAD

**Issue by jfrolich** [reason-react-native/reason-react-native#697]
`@bs.unwrap` (https://bucklescript.github.io/bucklescript/Manual.html#_using_polymorphic_variant_to_model_arguments_of_multiple_possible_types_since_1_8_3) can unwrap polymorphic variants to only pass the underlying value. This means we can have a nicer way to model transforms:

```
~transform=[|
   `translateY({translateY}),
|]
```

instead of:

```
~transform=[|
  translateY(~translateY),
|]
```

BTW we can keep the old function around.

**Comment by MoOx** [comment]
I see more char on the first snippet than the second one. 
What are the benefits?

**Comment by MoOx** [comment]
@jfrolich up to my previous question: what is the point of the change? Are the bindings less verbose somehow?

**Comment by jfrolich** [comment]
Yeah was just an idea, but agree it's probably not worth a change.
