### ISSUE TITLE
bs-platform 8.0.0 breaks Style.list

### ISSUE THREAD

**Issue by cknitt** [reason-react-native/reason-react-native#699]
BuckleScript 8 changed the encoding of `list`, so `Style.list` does not work anymore.

`Style.list([style1, style2])` now gets compiled to

```js
{
  hd: style1,
  tl: {
    hd: style2,
    tl: /* [] */0
  }
}
```

My suggestion is to deprecate `Style.list`, adding a warning saying that it's incompatible with BS8 and `Style.array` should be used instead, and remove it in one of the next versions.

/cc @MoOx

**Comment by cknitt** [comment]
(Same goes for `Style.listOption`.)

**Comment by jfrolich** [comment]
Yeah ran into that as well. I think we need to deprecate `Style.list`.

**Comment by MoOx** [comment]
Ok we can deprecate this asap indeed.
