### ISSUE TITLE
Type of TouchableNativeFeedback.Background.canUseNativeForeground

### ISSUE THREAD

**Issue by phamhoaivu911** [reason-react-native/reason-react-native#702]
## The problem
Please correct me if I'm wrong. From the [doc](https://reactnative.dev/docs/touchablenativefeedback#useforeground), we're supposed to call `canUseNativeForeground` and pass its result to `useForeground`. 

So the type of [TouchableNativeFeedback.Background.canUseNativeForeground](https://github.com/reason-react-native/reason-react-native/blob/master/src/components/TouchableNativeFeedback.re#L14) should be `unit => bool`

## Expected behavior
The type of `TouchableNativeFeedback.Background.canUseNativeForeground` should be `unit => bool`
## Actual behavior
The type of `TouchableNativeFeedback.Background.canUseNativeForeground` is `unit => Background.t`

**Comment by MoOx** [comment]
Yes indeed ! 
Confirmed by https://github.com/facebook/react-native/blob/72285d808dfce748287a19e2620d58517a5f76e7/Libraries/Components/Touchable/TouchableNativeFeedback.js#L164

Could you make a PR to handle this @phamhoaivu911 ?

**Comment by phamhoaivu911** [comment]
Hi @MoOx , I created a PR https://github.com/reason-react-native/reason-react-native/pull/704. Please take a look and let me know if I have to update anything. Thank you!
