### ISSUE TITLE
Messed up types for ScrollEvent payload

### ISSUE THREAD

**Issue by lazarevand1997** [reason-react-native/reason-react-native#706]
### Here messed up types of contentInset and contentOffset

https://github.com/reason-react-native/reason-react-native/blob/499c6d3e71b92261afbcae3d2d3784ddb314668a/src/apis/Event.re#L169-L174

## Expected behavior

```
type payload = {
    contentInset: contentInset,
    contentOffset: contentOffset,
    contentSize: dimensions,
    layoutMeasurement: dimensions,
  };
```

**Comment by MoOx** [comment]
bindings in 0.62.2 are available and should fix that :)
