### ISSUE TITLE
RRN doesn't compile on BS8.2

### ISSUE THREAD

**Issue by jfrolich** [reason-react-native/reason-react-native#707]
Due to warnings about redundant use of `bs.string`. Obviously we cannot refactor those yet because of backwards compatibility. But the setting of warnings as errors is not correct. We shouldn't enforce that as a dependency. This means that projects will stop compiling once a future version of Bucklescript has warnings of certain things.

**Comment by MoOx** [comment]
You mean that our setting to block compilation on warnings affect users of this lib?! I was thinking that this settings is internal 😱
If that the case, we should either: just change this, or change this before publication of the repo (should be easy to do)

**Comment by jfrolich** [comment]
Or perhaps run bsb with a flag on the CI? Anyway I posted a PR to fix this in the short term. Would be good to expedite this before everyone starts upgrading.

**Comment by MoOx** [comment]
I guess we could add this flag by hand in a script yeah.

**Comment by cknitt** [comment]
I think this can be closed now?

**Comment by MoOx** [comment]
I guess yeah for now...

**Comment by MoOx** [comment]
FYI I am going to push this change in all repo https://github.com/reason-react-native/safe-area-context/pull/4
