### ISSUE TITLE
Using `requireNativeComponent` 

### ISSUE THREAD

**Issue by idkjs** [reason-react-native/reason-react-native#709]
I'm trying to use `` with out success.

I have this code which compiles but leaves me a blank space where the button should be.

```reason
[@bs.module "react-native"]
external requireNativeComponent:
  (string, [@bs.as {json|null|json}] _) => React.component('a) =
  "requireNativeComponent";

let requireNativeComponent = name =>
  requireNativeComponent(name, Js.Null.empty);
let signInWithAppleButton = requireNativeComponent("SignInWithAppleButton");
  
[@genType]
let default = signInWithAppleButton;
```

This throw with error:
```
  Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

```
 Who's `tsx` equivalent is:

```tsx
import { requireNativeComponent, NativeModules } from "react-native";

export let SignInWithAppleButton = requireNativeComponent(
  "SignInWithAppleButton"
);

```

Thank you.

**Comment by MoOx** [comment]
You are not exporting the same thing in the ts code and the reasonml one. One export `SignInWithAppleButton` and the reasonml export `signInWithAppleButton`and `default`.

**Comment by idkjs** [comment]
Thanks, @MoOx! I cant give my export a capital name with `let`, would I call that?

**Comment by idkjs** [comment]
I tried

```reason
[@genType]
let signInWithAppleButton = requireNativeComponent("SignInWithAppleButton");
```

The calling with:
```tsx
import  {signInWithAppleButton as SignInWithAppleButton}
 from "./components/SignInWithAppleIOSButton.gen";
```

Same error.

This is the generated .tsx

```
export type Props = {};

export const $$default: React.ComponentType<{}> = SignInWithAppleIOSButtonBS.default;

export default $$default;
```

I am thinking this should do something. It's not not throwing but just comes up blank.

<img width="351" alt="Screen Shot 2020-08-06 at 7 14 05 PM" src="https://user-images.githubusercontent.com/2370391/89591848-3ac51d00-d819-11ea-9a3a-3dacd3e3d006.png">

**Comment by MoOx** [comment]
Why is the generated ts calling `SignInWithAppleIOSButtonBS.default;` ?
Anyway, it's not a binding issue, more a gentype/user problem. Please come on discord for this kind of problem, hard to help via issue.

**Comment by idkjs** [comment]
I dont have to use gentype. I tried with `bs.module` too. I maybe don't know enough about native modules. I would like to produce and example to add to the docs. If I had the question, maybe others did.

**Comment by MoOx** [comment]
Where does your SignInWithAppleButton comes from? Is the native module working with standard JS code?
If that's not the case make it work for JS, then try using binding to produce similar JS.

If you can't produce the same output, please try discord again.
