### ISSUE TITLE
separatorComponentProps etc. should be Js.t objects, not records

### ISSUE THREAD

**Issue by cknitt** [reason-react-native/reason-react-native#719]
It seems we somewhat overdid the Js.t -> record thing. 😉 

FlatList has the prop

```reason
~_ItemSeparatorComponent: React.component(separatorComponentProps('item))
```

with

```reason
type separatorComponentProps('item) = {
  highlighted: bool,
  leadingItem: option('item),
};
```

Previously when `separatorComponentProps` was still a Js.t type, I could have something like

```reason
module MySeparator = {
  [@react.component]
  let make = (~highlighted as _: bool, ~leadingItem as _: option('item)) => <View style=styles##separator />;
};
```

and do

```reason
<FlatList _ItemSeparatorComponent=MySeparator.make />
```

Now this is not possible anymore. The reason is that the JSX PPX uses Js.t types, not record types, so the prop type generated by the JSX PPX does not match with our declaration of `separatorComponentProps`.

I would therefore like to revert to Js.t in all affected places (I think there are are just a few in FlatList and VirtualizedList).

@MoOx Do you agree?

**Comment by MoOx** [comment]
Yeah looks like a legit use case to revert.

**Comment by cknitt** [comment]
Ok, will prepare a PR.
